# Generated by Django 4.2.5 on 2023-11-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_alter_recipename_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipename',
            name='recipe_image',
            field=models.ImageField(upload_to='vege/recipes'),
        ),
    ]
