# Generated by Django 4.2.5 on 2023-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_alter_recipename_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipename',
            name='recipe_desciption',
            field=models.TextField(max_length=1000),
        ),
    ]
